"use client"

import Link from "next/link"
import { usePathname } from "next/navigation"
import { ChevronRight, Home } from "lucide-react"

const pathNames: Record<string, string> = {
  dashboard: "Dashboard",
  invoices: "Fakturácia",
  accounting: "Účtovníctvo",
  bank: "Banka",
  "cash-register": "Pokladňa",
  warehouse: "Sklad",
  payroll: "Mzdy",
  travel: "Cestovné príkazy",
  taxes: "Dane",
  closing: "Závierka",
  reports: "Reporty",
  contacts: "Kontakty",
  assets: "Majetok",
  settings: "Nastavenia",
  "ai-assistant": "AI Asistent",
  new: "Nový",
  edit: "Upraviť",
  journal: "Denník",
  ledger: "Hlavná kniha",
  vat: "DPH",
  "control-statement": "Kontrolný výkaz",
  recurring: "Opakované faktúry",
  quotes: "Cenové ponuky",
  orders: "Objednávky",
  documents: "Dokumenty",
  "chart-of-accounts": "Účtový rozvrh",
  "cost-centers": "Strediská",
  projects: "Projekty",
  predkontacie: "Predkontácie",
  "trial-balance": "Obratová predvaha",
  "number-check": "Kontrola číslovania",
  subledger: "Saldokonto",
  receivables: "Pohľadávky",
  payables: "Záväzky",
  aging: "Aging analýza",
  transactions: "Transakcie",
  book: "Pokladničná kniha",
  seed: "Načítať predvolené",
  post: "Zaúčtovať",
  reverse: "Stornovať",
  accounts: "Účty",
  statements: "Výpisy",
  import: "Import",
  matching: "Párovanie",
  rules: "Pravidlá",
  pair: "Spárovať",
  unpair: "Odpárovať",
  approve: "Schváliť",
  download: "Stiahnuť",
  "mark-sent": "Odoslané",
  "from-invoices": "Z faktúr",
  dph: "DPH",
  kvdph: "Kontrolný výkaz",
  sv: "Súhrnný výkaz",
  "income-tax": "Daň z príjmov",
  dppo: "DPPO",
  dpfo: "DPFO",
  depreciation: "Odpisy",
  categories: "Kategórie",
  calculate: "Vypočítať",
  submit: "Odoslať",
  "download-xml": "Stiahnuť XML",
  "depreciation-summary": "Prehľad odpisov",
  dispose: "Vyradiť",
  depreciate: "Odpísať",
  checklist: "Checklist",
  operations: "Uzávierkové operácie",
  "period-lock": "Uzamknutie obdobia",
  "opening-balances": "Počiatočné stavy",
  "balance-sheet": "Súvaha",
  "profit-loss": "Výkaz ziskov a strát",
  notes: "Poznámky",
  "ruz-export": "RÚZ export",
  generate: "Generovať",
  lock: "Uzamknúť",
  unlock: "Odomknúť",
  preview: "Náhľad",
  finalize: "Finalizovať",
  employees: "Zamestnanci",
  "payroll-run": "Spracovanie miezd",
  payslips: "Výplatné pásky",
  "payroll-list": "Výplatná listina",
  contracts: "Zmluvy",
  attendance: "Dochádzka",
  leave: "Dovolenka",
  "sick-leave": "PN",
  deductions: "Zrážky",
  "tax-declarations": "Daňové hlásenia",
  "monthly-report": "Mesačný prehľad",
  "annual-report": "Ročné hlásenie",
  "sp-report": "Výkaz SP",
  "zp-report": "Výkaz ZP",
  "tax-certificate": "Potvrdenie o príjmoch",
  "annual-settlement": "Ročné zúčtovanie",
  run: "Spustiť",
  "travel-orders": "Cestovné príkazy",
  domestic: "Tuzemské",
  foreign: "Zahraničné",
  settlement: "Vyúčtovanie",
  advance: "Preddavok",
  vehicle: "Vozidlo",
  meals: "Stravné",
  expenses: "Výdavky",
  accommodation: "Ubytovanie",
  "per-diem": "Diéty",
  countries: "Krajiny",
  rates: "Sadzby",
  products: "Produkty",
  "stock-receipt": "Príjemky",
  "stock-issue": "Výdajky",
  "stock-transfer": "Prevodky",
  inventory: "Inventúra",
  "stock-card": "Skladové karty",
  "stock-status": "Stav zásob",
  "stock-turnover": "Obratovka",
  "abc-analysis": "ABC analýza",
  "price-levels": "Cenové hladiny",
  "min-stock": "Minimálne zásoby",
  warehouses: "Sklady",
  movements: "Pohyby",
  batches: "Šarže",
  "financial-reports": "Finančné reporty",
  "aging-receivables": "Aging pohľadávok",
  "aging-payables": "Aging záväzkov",
  "cash-flow": "Cash flow",
  "cash-flow-forecast": "Prognóza cash flow",
  profitability: "Rentabilita",
  "period-comparison": "Porovnanie období",
  "product-margin": "Marža na produkt",
  "top-customers": "Top odberatelia",
  "top-suppliers": "Top dodávatelia",
  "unpaid-invoices": "Neuhradené faktúry",
  "break-even": "Break-even analýza",
  "financial-indicators": "Finančné ukazovatele",
  "statistics": "Štatistické výkazy",
  widgets: "Widgety",
  "auditor-export": "Export pre audítora",
  notifications: "Notifikácie",
  "notification-rules": "Pravidlá",
  "notification-center": "Centrum notifikácií",
  "email-templates": "Emailové šablóny",
  "audit-log": "Audit log",
  archive: "Archív",
  gdpr: "GDPR",
  "data-export": "Export údajov",
  anonymize: "Anonymizácia",
  backup: "Zálohovanie",
  restore: "Obnova",
  "api-keys": "API kľúče",
  webhooks: "Webhooky",
  integrations: "Integrácie",
  "import-wizard": "Import wizard",
  "exchange-rates": "Kurzový lístok",
  profile: "Profil",
  company: "Firma",
  "fiscal-years": "Fiškálne roky",
  numbering: "Číslovanie",
  users: "Používatelia",
  roles: "Roly",
  "e-signature": "Elektronický podpis",
  "e-dane": "eDane",
  "ekasa": "eKasa",
  "xml-validation": "Validácia XML",
  "submitted-returns": "Podané priznania",
  portal: "Klientský portál",
  payments: "Platby",
  stripe: "Stripe",
  gopay: "GoPay",
  "pay-by-square": "PAY by square",
  "payment-links": "Platobné linky",
  "import-data": "Import dát",
  "pohoda-import": "Pohoda import",
  "csv-import": "CSV import",
  "multi-currency": "Multi-mena",
  "currency-rates": "Kurzový lístok",
  "currency-revaluation": "Precenenie",
  consolidation: "Konsolidácia",
  "intercompany": "Intercompany",
}

export function Breadcrumb() {
  const pathname = usePathname()
  const segments = pathname.split("/").filter(Boolean)

  if (segments.length <= 1) return null

  return (
    <nav className="flex items-center gap-1 text-sm text-muted-foreground mb-4">
      <Link href="/dashboard" className="hover:text-foreground">
        <Home className="h-4 w-4" />
      </Link>
      {segments.map((segment, index) => {
        const href = "/" + segments.slice(0, index + 1).join("/")
        const isLast = index === segments.length - 1
        const name = pathNames[segment] || segment

        return (
          <span key={href} className="flex items-center gap-1">
            <ChevronRight className="h-3 w-3" />
            {isLast ? (
              <span className="text-foreground font-medium">{name}</span>
            ) : (
              <Link href={href} className="hover:text-foreground">
                {name}
              </Link>
            )}
          </span>
        )
      })}
    </nav>
  )
}
